### ISSUE TITLE
Can you give me the "vocab.txt" ? thank you

### ISSUE THREAD

**Issue by HappyLife-together** [clips/clicr#2]
neural-readers/ga-reader/utils/DataPreprocessor.py", line 802, in make_dictionary
    vocab_fp = open(vocab_file, "w")
FileNotFoundError: [Errno 2] No such file or directory: 'data/wdw/vocab.txt'

**Comment by SimonSuster** [comment]
Have you checked that `data/wdw/` exists ? Here, vocabulary is created based on the your data, and then written to vocab.txt

**Comment by HappyLife-together** [comment]
‘data/wdw/’ were not created, I am looking at the code, thank you
